on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Cache Buildozer .buildozer folder
        uses: actions/cache@v4
        with:
          path: |
            .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('**/*.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.11
          buildozer-cmd: |
            pip install --upgrade pip setuptools wheel
            pip install buildozer
            buildozer android update
            buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk
